### ISSUE TITLE
Register ADCAD with BioPortal

### ISSUE THREAD

**Issue by amoeba** [NCEAS/adc-disciplines#7]

**Comment by amoeba** [comment]
ADCAD 1.0.0 has been submitted. It takes a few days to get fully indexed so the [landing page](https://bioportal.bioontology.org/ontologies/ADCAD) is live but not working.

I'll update here next week when it's all set.

**Comment by amoeba** [comment]
ADCAD is fully processed on BioPortal at https://bioportal.bioontology.org/ontologies/ADCAD.

**Comment by mbjones** [comment]
Thanks!
